version: '3.9'
services:
  redis:
    image: redis:7
    container_name: redis

  nestjs:
    build: .
    container_name: nestjs
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
