# Expose nestjs through nodeport
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  labels:
    app: nestjs-app
spec:
  type: NodePort      #access from outside cluster
  selector:
    app: nestjs-app   # matches pod label
  ports:
    - port: 3000    #service port
      targetPort: 3000  #pod port
      nodePort: 30001   #port for external access
